# Career development

This page will mostly focus on academic career development. For advice about transitioning into a non-academic career path, you may wish to get in touch with the University's [career center](https://sheffield.ac.uk/careers). Alternatively, for researchers interested in translating their findings into real world applications, the [knowledge exchange team](https://sheffield.ac.uk/science/collaborate) would be a good point of contact.

The academic career path is broadly PhD -\> postdoc -\> independent group leader. Each of these points of transition can be quite competitive, requiring evidence of high-quality outcomes at previous stages.

## Fellowships

[Independent fellowships](https://sites.google.com/sheffield.ac.uk/guide-to-fellowships-at-uos/guide) can be a big boost to your progress. These are parcels of money that are awarded to you as an individual on the basis of your proven track record and an excellent research proposal. These are available at all career stages, but the most critical are the transition to independence fellowships (typically pursued after a few years of postdoctoral experience). Such fellowships are now often the only route to a permanent job at UK research universities.

Regardless of the career stage that is being applied for, you will need to be able to answer three key questions:

-   What is the project?

-   Why am I the best person to carry it out?

-   Why is my chosen institution/group the best place to carry it out?

If you can answer all three of those questions convincingly, you may be ready to apply.

For those interested, [this page](https://sheffield.ac.uk/science/research/fellowships) provides further details on the schemes that Sheffield supports. I would be very happy to discuss ideas with you, although a critical factor in succeeding in such schemes is that your ideas are clearly distinctive from other peoples'. The degree of independent idea development depends on your career stage, increasing as you move up the career ladder.

## Other opportunities

You may also wish to apply for other sources of money.
